NRIのhtmlの提出です
KakoFujimoto/html_and_js pull request #1
Opened 2020-03-28 10:40 UTC by KakoFujimoto

2020-03-31 05:39 UTC, nozomi71 commented on index.html
> +        </ul>
これは`nav`じゃなくていいですかね？

2020-03-31 05:39 UTC, nozomi71 commented on index.html
> +            <article>
これは`article`ではないですね

2020-03-31 05:39 UTC, nozomi71 commented on index.html
> +            <div class="power">
ここ`section`じゃなくていいですかね？

2020-03-31 05:39 UTC, nozomi71 commented on index.html
> +            </ul>
h3が出てくるなら`section`でかこいたいですね

2020-03-31 05:39 UTC, nozomi71 commented on index.html
> +                </li>
`li`に見出しがくることはないです

2020-03-31 05:39 UTC, nozomi71 commented on index.html
> +        <section>
見出しが直下にこないなら`section`じゃなくてOKです

2020-03-31 07:33 UTC, KakoFujimoto commented on index.html
> +        </ul>
パンクズかと思ってました・・！！navに入れました・・！

2020-03-31 07:33 UTC, KakoFujimoto commented on index.html
> +            <article>
はいっ・・・

2020-03-31 07:38 UTC, KakoFujimoto commented on index.html
> +            <div class="power">
いえっ・・・

2020-03-31 07:40 UTC, KakoFujimoto commented on index.html
> +        <section>
かしこまりましたっ！

2020-03-31 07:43 UTC, KakoFujimoto commented on index.html
> +                </li>
そのあたり全体的にpに直しました・・！

2020-03-31 08:18 UTC, KakoFujimoto commented on index.html
> +                </li>
かしこまりました。見かけはcss当てます。

2020-03-31 08:42 UTC, KakoFujimoto commented on index.html
> +            </ul>
わかりました・・！

2020-03-31 12:45 UTC, nozomi71 commented on index.html
> +            <p>NRI では、企業の DX に向けた取り組みについて、既存ビジネスの業務プロセス変革に寄与する DX を「DX1.0」、デジタルで新しいビジネスモデルそのものを生み出す DX
h1が2つありますね

2020-03-31 12:45 UTC, nozomi71 commented on index.html
> +        </section>
見出しないなら`section`は適当ではないです

2020-03-31 12:45 UTC, nozomi71 commented on index.html
> +            <small>Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</small>
`small`タグは使わずcssで修飾しましょう

2020-03-31 13:29 UTC, KakoFujimoto commented on index.html
> +            <p>NRI では、企業の DX に向けた取り組みについて、既存ビジネスの業務プロセス変革に寄与する DX を「DX1.0」、デジタルで新しいビジネスモデルそのものを生み出す DX
ご指摘のh1のうち、３０行目のh1をh2に、今までh2だった他の部分を全てh3に変更しました。

2020-03-31 13:30 UTC, KakoFujimoto commented on index.html
> +            <small>Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</small>
！！！今、質問チャンネルでの回答待ちです！！！

2020-03-31 13:31 UTC, KakoFujimoto commented on index.html
> +        </section>
承知しました。sectionを削除し、ulにclass付けしました。

2020-03-31 13:56 UTC, KakoFujimoto commented on index.html
> +            <small>Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</small>
addressの方が主流のようなので今回addressに変更しました（html5ではCopyrightはsmallで囲うようになったという意見もあり）

2020-04-01 03:50 UTC, piasoratech approved these changes
OKです！
1点だけコメントしたので確認してもらって、次に進んでもらって大丈夫です！

2020-04-01 03:50 UTC, piasoratech commented on index.html
> +            <ul class="breadcrumb">
細かいですがパンくずリストとしての命名であれば`breadcrumbs`が正しいです。もしくは`breadcrumb list`ですね

2020-04-01 04:26 UTC, KakoFujimoto commented on index.html
> +            <ul class="breadcrumb">
複数形なのですね。承知しました！

2020-04-07 01:27 UTC, piasoratech requested changes
CSSの構文チェックをかけるとエラーが出てくるので、解消して再提出お願いします
構文チェッカーは以下のURLを使用しています。
https://jigsaw.w3.org/css-validator/validator.html.ja#validate_by_input

2020-04-07 01:49 UTC, KakoFujimoto commented
> CSSの構文チェックをかけるとエラーが出てくるので、解消して再提出お願いします
> 構文チェッカーは以下のURLを使用しています。
> https://jigsaw.w3.org/css-validator/validator.html.ja#validate_by_input

margin当たってなかったのでその行を削除しました

2020-04-08 02:35 UTC, piasoratech requested changes
![image](https://user-images.githubusercontent.com/57445698/78738521-089bcf80-798d-11ea-84fe-4eb01edd7bc7.png)
もしかするとファイルが巻き戻っているかもしれないです…

2020-04-08 04:53 UTC, KakoFujimoto commented
> ![image](https://user-images.githubusercontent.com/57445698/78738521-089bcf80-798d-11ea-84fe-4eb01edd7bc7.png)
> もしかするとファイルが巻き戻っているかもしれないです…

この問題、原因が分かりました。
実際にはファイルは巻き戻っておらず、構文チェッカーでチェックする時に「直接入力」するか「アップロード」するかによって結果が変わることを確認しました。
具体的に言うと、直接入力した場合は
```
nav ul {
    list-style:none;
}

blockquote, q {
    quotes:none;
}
```
などのulの後のスペースや、nav ulとblockquote, qの間の改行がNG判定され、検証結果もNGとなってしまうようです。
スペースや改行があっても、アップロードする方式だと検証 OKとなるようです。

今回、いずれのパターンでも判定OKに修正しています。

2020-04-09 06:06 UTC, Yuzunoha commented on html-nri/index.html
> +        <div class="links">
ここのul

ナレッジ・インサイト、ソリューション・サービス、サステナビリティ、...

本家に習って2段になるようにしてください～

2020-04-09 07:11 UTC, KakoFujimoto commented on html-nri/index.html
> +        <div class="links">
<img width="1116" alt="スクリーンショット 2020-04-09 16 10 01" src="https://user-images.githubusercontent.com/60574321/78867829-bd60ea00-7a7c-11ea-8ad9-1c006e37c8d8.png">
こう言うことですねことですね！　実装しました！

2020-04-09 07:54 UTC, Yuzunoha commented on html-nri/index.html
> +        <div class="links">
すみませんこれことじゃないです><
とはいえ確実に良くなったのでこれはナイスなアップデートです！！

当初の意図はこういうことでした！
右端がニュースの見出し固定で、画面を横長にしても確実に2段になるようにということです。

必要であればhtmlファイルも修正してください

![nri](https://user-images.githubusercontent.com/22877094/78871518-c94faa80-7a82-11ea-8384-0068beed8e01.JPG)

2020-04-09 11:45 UTC, KakoFujimoto commented on html-nri/index.html
> +        <div class="links">
完全に理解しました…！
２段に分けました！

2020-04-09 16:06 UTC, piasoratech requested changes
- ここめちゃくちゃ左に寄ってます…
![image](https://user-images.githubusercontent.com/57445698/78915590-1f464180-7ac7-11ea-90c4-5fc6af869f2d.png)
- あとここもですね
![image](https://user-images.githubusercontent.com/57445698/78915628-2c633080-7ac7-11ea-9d52-6ab349480e36.png)

- ここの並びの`>`が本家の位置とずれてます。
![image](https://user-images.githubusercontent.com/57445698/78915714-50267680-7ac7-11ea-9960-e2bd3df25ffd.png)
- ヘッダー部分マークアップ漏れがあったので修正をお願いします(チェック漏れててすいません…)
![image](https://user-images.githubusercontent.com/57445698/78915787-6b918180-7ac7-11ea-96e6-d40d9e7aa93a.png)

2020-04-10 00:44 UTC, KakoFujimoto commented
> * ここめちゃくちゃ左に寄ってます…
>   ![image](https://user-images.githubusercontent.com/57445698/78915590-1f464180-7ac7-11ea-90c4-5fc6af869f2d.png)
> * あとここもですね
>   ![image](https://user-images.githubusercontent.com/57445698/78915628-2c633080-7ac7-11ea-9d52-6ab349480e36.png)
> * ここの並びの`>`が本家の位置とずれてます。
>   ![image](https://user-images.githubusercontent.com/57445698/78915714-50267680-7ac7-11ea-9960-e2bd3df25ffd.png)
> * ヘッダー部分マークアップ漏れがあったので修正をお願いします(チェック漏れててすいません…)
>   ![image](https://user-images.githubusercontent.com/57445698/78915787-6b918180-7ac7-11ea-96e6-d40d9e7aa93a.png)



> * ここめちゃくちゃ左に寄ってます…
>   ![image](https://user-images.githubusercontent.com/57445698/78915590-1f464180-7ac7-11ea-90c4-5fc6af869f2d.png)
> * あとここもですね
>   ![image](https://user-images.githubusercontent.com/57445698/78915628-2c633080-7ac7-11ea-9d52-6ab349480e36.png)
> * ここの並びの`>`が本家の位置とずれてます。
>   ![image](https://user-images.githubusercontent.com/57445698/78915714-50267680-7ac7-11ea-9960-e2bd3df25ffd.png)
> * ヘッダー部分マークアップ漏れがあったので修正をお願いします(チェック漏れててすいません…)
>   ![image](https://user-images.githubusercontent.com/57445698/78915787-6b918180-7ac7-11ea-96e6-d40d9e7aa93a.png)

<img width="1135" alt="スクリーンショット 2020-04-10 9 41 43" src="https://user-images.githubusercontent.com/60574321/78952222-d49ce780-7b0f-11ea-896a-b86a55ee0310.png">
<img width="1010" alt="スクリーンショット 2020-04-10 9 30 31" src="https://user-images.githubusercontent.com/60574321/78952233-de264f80-7b0f-11ea-996f-5f26eb068fce.png">
<img width="1087" alt="スクリーンショット 2020-04-10 9 42 47" src="https://user-images.githubusercontent.com/60574321/78952238-e088a980-7b0f-11ea-945e-dc487e773220.png">

2020-04-10 01:45 UTC, KakoFujimoto commented
> > * ここめちゃくちゃ左に寄ってます…
> >   ![image](https://user-images.githubusercontent.com/57445698/78915590-1f464180-7ac7-11ea-90c4-5fc6af869f2d.png)
> > * あとここもですね
> >   ![image](https://user-images.githubusercontent.com/57445698/78915628-2c633080-7ac7-11ea-9d52-6ab349480e36.png)
> > * ここの並びの`>`が本家の位置とずれてます。
> >   ![image](https://user-images.githubusercontent.com/57445698/78915714-50267680-7ac7-11ea-9960-e2bd3df25ffd.png)
> > * ヘッダー部分マークアップ漏れがあったので修正をお願いします(チェック漏れててすいません…)
> >   ![image](https://user-images.githubusercontent.com/57445698/78915787-6b918180-7ac7-11ea-96e6-d40d9e7aa93a.png)
> 
> > * ここめちゃくちゃ左に寄ってます…
> >   ![image](https://user-images.githubusercontent.com/57445698/78915590-1f464180-7ac7-11ea-90c4-5fc6af869f2d.png)
> > * あとここもですね
> >   ![image](https://user-images.githubusercontent.com/57445698/78915628-2c633080-7ac7-11ea-9d52-6ab349480e36.png)
> > * ここの並びの`>`が本家の位置とずれてます。
> >   ![image](https://user-images.githubusercontent.com/57445698/78915714-50267680-7ac7-11ea-9960-e2bd3df25ffd.png)
> > * ヘッダー部分マークアップ漏れがあったので修正をお願いします(チェック漏れててすいません…)
> >   ![image](https://user-images.githubusercontent.com/57445698/78915787-6b918180-7ac7-11ea-96e6-d40d9e7aa93a.png)
> 
> <img alt="スクリーンショット 2020-04-10 9 41 43" width="1135" src="https://user-images.githubusercontent.com/60574321/78952222-d49ce780-7b0f-11ea-896a-b86a55ee0310.png">
> 
> <img alt="スクリーンショット 2020-04-10 9 30 31" width="1010" src="https://user-images.githubusercontent.com/60574321/78952233-de264f80-7b0f-11ea-996f-5f26eb068fce.png">
> 
> <img alt="スクリーンショット 2020-04-10 9 42 47" width="1087" src="https://user-images.githubusercontent.com/60574321/78952238-e088a980-7b0f-11ea-945e-dc487e773220.png">

<img width="1311" alt="スクリーンショット 2020-04-10 10 43 59" src="https://user-images.githubusercontent.com/60574321/78954862-60b30d00-7b18-11ea-849d-94f9ef0f5eaa.png">

2020-04-10 04:10 UTC, piasoratech approved these changes
良いかと！

2020-04-10 04:29 UTC, Yuzunoha approved these changes
ユズノハ的にもOKです！！(ﾟ∀ﾟ)

2020-04-10 04:49 UTC, merged