家具屋topのhtmlの提出です
KakoFujimoto/html_and_js pull request #2
Opened 2020-04-01 05:40 UTC by KakoFujimoto

2020-04-01 09:27 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
タグの要素とかはとてもよく細かく調べられて使えているのでとても良いと思います！！！

2020-04-01 09:27 UTC, piasoratech commented on top.html
> +    <section class="section01">
`class`名や`id`名をxxxx01のように命名するのはやめましょう。
その名前を見ただけでどんな内容が書いてあるのか分かるような命名をするのが良いです。
他の部分も同様です！

2020-04-01 09:27 UTC, piasoratech commented on top.html
> +                <p>アームストロングのカウチ入荷</p>
ここに`p`タグを使った意図ってなんでしょうか？(他の同じような部分も)

2020-04-01 10:16 UTC, KakoFujimoto commented on top.html
> +    <section class="section01">
かしこまりました！自分なりにそれらしい名前を付けてみたので、ご確認をお願いします！

2020-04-01 10:29 UTC, KakoFujimoto commented on top.html
> +                <p>アームストロングのカウチ入荷</p>
前に見本がアニメーションになってた時に、実装の仕方が分からず、どこかのサイトを参考にした際の残りカスだと思われます。figcaption自体が画像の説明文という意味合いかと思われますので、外しました。

2020-04-03 03:37 UTC, piasoratech approved these changes
ＯＫです！

2020-04-07 05:45 UTC, fjtawork reviewed
確認お願いします。

2020-04-07 05:45 UTC, fjtawork commented on html-kaguya/news.html
> +    <title>We propose a life.</title>
titleタグはページごとに変えましょう！
そのページを説明する言葉にします。

2020-04-07 05:45 UTC, fjtawork commented on html-kaguya/top.html
> +                </figcaption>
インデントを調整しましょう

2020-04-07 11:10 UTC, KakoFujimoto commented on html-kaguya/news.html
> +    <title>We propose a life.</title>
変更しました。

2020-04-07 11:10 UTC, KakoFujimoto commented on html-kaguya/top.html
> +                </figcaption>
調整しました。

2020-04-08 08:34 UTC, yusaku-inamura requested changes
htmlチェッカーでエラーが出ているようです、少しでも変更があれば提出前に全ファイルチェック通すなどして、html文法的に問題のある状態でPRが出ないように気をつけてみてください。
とりあえず今回は途中までレビューしてしまったのでコメントしてます、確認お願いします。

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/contact.html
> +                <li><img class="header-logo" src="images/logo_header@2x.png" alt="HTMLCSS"></li>
この要素(ロゴ画像)がナビゲーションとしてマークアップされているのは少し不適切かもしれませんね。
この要素はヘッダーの要素ではありますが、他の `nav` 内の要素のようにページのツリー構造をメニュー化したものではないので、navの外に出すべきかなと。

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/contact.html
> +                <li><img class="header-logo" src="images/logo_header@2x.png" alt="HTMLCSS"></li>
もう一点imgのalt属性についても極力画像の補足となるようなテキストを入れておくのが良いです。
SEO的観点の話なのですが、いわゆる検索エンジン用のwebクローラには画像の情報が視覚的に取り込めないため、alt属性の値を読み込むからですね。
その他スクリーンリーダの読み上げ時にも活用される等、単なる画像リソースが取得できない場合の代替テキスト以外にも多くの役目がありますので少し調べてみてください。

今回は課題用のダミーサイトのためそこまで深く考えなくても大丈夫ですので、少しだけ考えてみましょう。

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/contact.html
> +                <li><a href="#">HOME</a></li>
ナビゲーション用のaタグ群は、遷移先のページについても指定して遷移できるようにしてしまいましょう。

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/contact.html
> +
不要な改行は削除するべきですね

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/contact.html
> +        <address>@HTMLCSS.code</address>
これデザイン側の間違いでめっちゃ申し訳ないのですが実は `@` ではなく `©︎` なのです・・・。
コピーライトだという前提で上で再度マークアップ考えてみてください 🙇 
文も `©︎` に直してしまっていただけると 😓

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/news.html
> +                <li><a href="#"><span>NEWS</span></a></li>
このspan必要ですかね?

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/news.html
> +                    <img src="images/imgD.png" alt="アームストロングのカウチ入荷">
figcaptionと同じ内容をimgタグのalt属性に指定するのはあまりよくないかもしれませんね。
figcaptionは図表の説明などですが、imgタグのalt属性にはその画像がどのような画像かを表す文言を入れるべきかなと。

マークアップ 全般に言えることなのですが、良いマークアップというのはhtmlをみただけでそれぞれの要素が何を表すかがわかるようになっているマークアップのことです。
例えば目の見えない人なども使用するhtmlの読み上げ機能などを使用してここを読み上げた場合、 `アームストロングのカウチ入荷` という文章が二回続き、最終的にどのような画像が存在しているのかわからないかと思います。
ちょっと観点を変えてalt属性に何を入れるのが良いか調べてみてください。
と言ってもそんなに難しく考えなくても大丈夫です。

みた感じ全体的にマークアップ 自体は意味合いまで考えてよくできていると思いますので、細かいところにまで目を向けられるとよりぐっどだと思います 👍

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/contact.html
> +    <meta charset="UTF-8">
余談ですがhtml/cssはどちらかと言えば半角スペース4文字よりも2文字の方が多いかもですね。
でも正直方針次第ですし、4文字も違反ではないので全然このままでOKです。(ここら辺は深く突っ込み始めると宗教論争的な意味で闇が深い)
ほんとにただの余談でした。

2020-04-08 08:34 UTC, yusaku-inamura commented on html-kaguya/top.html
> +        <p><a href="#">view more</a><span>&nbsp;&nbsp;&gt;</p>
これhtmlのチェック通ってます?

2020-04-08 09:06 UTC, KakoFujimoto commented on html-kaguya/top.html
> +        <p><a href="#">view more</a><span>&nbsp;&nbsp;&gt;</p>
通っています。
pタグの中の改行は非推奨ではないはずです。

2020-04-08 09:11 UTC, KakoFujimoto commented on html-kaguya/top.html
> +        <p><a href="#">view more</a><span>&nbsp;&nbsp;&gt;</p>
実体参照の件でしょうか？
賛否両論あるでしょうからcss当てますね。

2020-04-08 09:29 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +    <meta charset="UTF-8">
<head>と<meta>の間の空白の話ですね。
VSCodeの保存時自動整形ツールの仕様かと…。
ちなみにコーディングでインデント揃える時、通常tabキー使いますよね。
調べたところ、そのデフォルトが半角4文字みたいですね。

宗教戦争の話、参考になりました。
確かに基準が個人によって一致しておらず、ファジーな世界ですので論理的に正解を絞れないのは辛いですね。

2020-04-08 09:37 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +                <li><img class="header-logo" src="images/logo_header@2x.png" alt="HTMLCSS"></li>
> この要素(ロゴ画像)がナビゲーションとしてマークアップされているのは少し不適切かもしれませんね。
> この要素はヘッダーの要素ではありますが、他の `nav` 内の要素のようにページのツリー構造をメニュー化したものではないので、navの外に出すべきかなと。

仰る評価基準は理解できます。
ですが、これらのhtml３種は全て最初に作った「TOP」ページとヘッダー部分とフッター部分は同じですよね。

であれば、TOPページのpr時にアルコーダーさんから指摘が入ってない箇所に稲村さんから指摘が入る体制は少し不自然かと。
評価基準を均一化して頂けないでしょうか。
手戻り感がすごいです。

2020-04-08 13:57 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +                <li><img class="header-logo" src="images/logo_header@2x.png" alt="HTMLCSS"></li>
> もう一点imgのalt属性についても極力画像の補足となるようなテキストを入れておくのが良いです。
> SEO的観点の話なのですが、いわゆる検索エンジン用のwebクローラには画像の情報が視覚的に取り込めないため、alt属性の値を読み込むからですね。
> その他スクリーンリーダの読み上げ時にも活用される等、単なる画像リソースが取得できない場合の代替テキスト以外にも多くの役目がありますので少し調べてみてください。
> 
> 今回は課題用のダミーサイトのためそこまで深く考えなくても大丈夫ですので、少しだけ考えてみましょう。

理解しました。それらしいalt属性を付けたので確認お願いします。

2020-04-08 14:08 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +                <li><a href="#">HOME</a></li>
それぞれにリンク先を指定しました。

2020-04-08 14:11 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +
処理しました。

2020-04-08 14:15 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +        <address>@HTMLCSS.code</address>
https://github.com/KakoFujimoto/NEWkadai03/pull/2


test03.html Outdated
            <li><a href="#">プライバシー規約</a></li>
            <li><a href="#">ヘルプ</a></li>
        </ul>
        <p class="copyright">&copy;1996-2020,Amazon.com,Inc. or its affiliates</p>
 @nozomi71
nozomi71 21 days ago
コピーライトはaddressタグがいいかな…

 @KakoFujimoto
KakoFujimoto 20 days ago Author Owner
かしこまりました！

2020-04-08 14:45 UTC, KakoFujimoto commented on html-kaguya/news.html
> +                <li><a href="#"><span>NEWS</span></a></li>
XDの見方が甘く、hover時の効果だと言う事を見過ごしておりました。
仰る通り不要なので削除しました。

2020-04-08 14:52 UTC, KakoFujimoto commented on html-kaguya/top.html
> +        <p><a href="#">view more</a><span>&nbsp;&nbsp;&gt;</p>
あと、top.htmlは今回のprではないのですが（前回アルコーダーさんによってLGTM頂いています）。今回、見過ごせないと言う認識でのご指摘なのでしょうか…？
（今回のprはtop以外の３つのhtmlです）

2020-04-08 15:03 UTC, KakoFujimoto commented on html-kaguya/news.html
> +                    <img src="images/imgD.png" alt="アームストロングのカウチ入荷">
ここのご指摘、大変参考になりました。
なるほど、そんな違いがあったんですね。勉強不足で恥ずかしいです。

> みた感じ全体的にマークアップ 自体は意味合いまで考えてよくできていると思います

すごく嬉しく励みになります…。ありがとうございます！

2020-04-09 09:12 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-09 09:12 UTC, piasoratech commented on html-kaguya/contact.html
> +                <textarea name="comment" id="comment">お問い合わせ内容</textarea><br>
ここは`value`指定より`placeholder`かなと思います。
`value`の場合だとフォームに入力されてしまっている状態になるので！
`textarea`の場合はタグで挟んでいる部分を空欄にして`placeholder`を指定すればOKです

2020-04-09 09:12 UTC, piasoratech commented on html-kaguya/news.html
> +                    <img src="images/imgD.png" alt="少しくすんだ青色のカウチです">
`少しくすんだ青色`っていい表現ですね
思わず笑ってしまいました。(指摘とかでは全くないです)

2020-04-09 11:21 UTC, KakoFujimoto commented on html-kaguya/news.html
> +                    <img src="images/imgD.png" alt="少しくすんだ青色のカウチです">
めっちゃ笑いましたw

2020-04-09 11:25 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +                <textarea name="comment" id="comment">お問い合わせ内容</textarea><br>
確かに・・！
修正致しました。

2020-04-09 15:48 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-04-10 05:11 UTC, KakoFujimoto commented
#家具屋TOPページcssの提出です
[5f15b15　こちらのコミットです](https://github.com/KakoFujimoto/KakoFujimoto/commit/5f15b1538a4df4ab0961a1000fa64ea873ec0b85)
##header nav内a要素のリンク効果アニメーションですが他言語が必要となるため、hover擬似要素にスタイル当ててます

2020-04-10 06:29 UTC, piasoratech reviewed
![image](https://user-images.githubusercontent.com/57445698/78968609-0332b680-7b40-11ea-9979-29a6601fce11.png)
全体的に右側に余白ができてしまっていますが、そちらではどうでしょうか？

2020-04-10 07:00 UTC, KakoFujimoto commented
ご指摘の箇所、修正しました。
<img width="1367" alt="スクリーンショット 2020-04-10 15 58 59" src="https://user-images.githubusercontent.com/60574321/78970456-4ee75f00-7b44-11ea-9a78-8b04cbdf3d91.png">

2020-04-10 07:10 UTC, piasoratech requested changes
指摘箇所を修正したことによって他の部分に影響が出ていないことは確認されたでしょうか？
私のほうではフッターの位置が変わっていたり、その他の部分で左右余白が大きくとられるようになってしまっていますが…

2020-04-10 08:17 UTC, KakoFujimoto commented
一部余白の指定方式を変えたり、flexbox内の配置方法を変更しました。

2020-04-10 08:22 UTC, piasoratech approved these changes
OKっす！
この短時間でさすがでございます！

2020-04-13 07:03 UTC, KakoFujimoto commented
家具屋3p分のcssです。クラス名付与など、htmlにも軽微なアプデがあるためhtmlもpushしています。

2020-04-13 07:47 UTC, piasoratech requested changes
・ヘッダーがアクセスしているページだけ文字色が濃くなっているはずなので、確認をお願いします。(HOMEのCSSのときに指摘漏れてました。すいません。)
![image](https://user-images.githubusercontent.com/57445698/79102727-3d9d8d00-7da6-11ea-94d0-500a3cecea28.png)

・家具職人の文字が水平方向で真ん中になっていないので直しましょう。
![image](https://user-images.githubusercontent.com/57445698/79102717-370f1580-7da6-11ea-8f1d-3a51a2255176.png)
・家具屋がオーダーできちゃいます…(マークアップのときの指摘漏れです。ごめんなさい。)
![image](https://user-images.githubusercontent.com/57445698/79102782-60c83c80-7da6-11ea-9066-d120349deba6.png)

2020-04-13 08:06 UTC, KakoFujimoto commented
<img width="687" alt="スクリーンショット 2020-04-13 16 59 19" src="https://user-images.githubusercontent.com/60574321/79104244-2613d380-7da9-11ea-80e6-bce881d78239.png">
<img width="573" alt="スクリーンショット 2020-04-13 16 59 56" src="https://user-images.githubusercontent.com/60574321/79104248-27dd9700-7da9-11ea-809a-c3b497519a04.png">
<img width="1160" alt="スクリーンショット 2020-04-13 17 05 48" src="https://user-images.githubusercontent.com/60574321/79104254-2ad88780-7da9-11ea-925b-6e904b4990d3.png">

2020-04-13 08:34 UTC, piasoratech requested changes
・NEWSの時だけヘッダーの文字が小さくなってしまうので確認をお願いします。
![image](https://user-images.githubusercontent.com/57445698/79106128-dcc58300-7dac-11ea-950c-eca620ccb069.png)
・見本の文面は「オーダー家具や在庫状況の…」なので、見本の通りに修正をお願いします。
![image](https://user-images.githubusercontent.com/57445698/79106205-01215f80-7dad-11ea-92e1-2852707842d7.png)

2020-04-13 08:43 UTC, KakoFujimoto commented
<img width="576" alt="スクリーンショット 2020-04-13 17 42 14" src="https://user-images.githubusercontent.com/60574321/79106889-50b45b00-7dae-11ea-86c3-70bd4255d5aa.png">
<img width="1146" alt="スクリーンショット 2020-04-13 17 43 01" src="https://user-images.githubusercontent.com/60574321/79106893-527e1e80-7dae-11ea-84e1-a9eb8f0559ff.png">

2020-04-13 08:46 UTC, piasoratech approved these changes
良いかと！

2020-04-15 03:56 UTC, KakoFujimoto commented
#  家具屋TOPのレスポンシブデザイン提出です

[76100a7](https://github.com/KakoFujimoto/KakoFujimoto/pull/2/commits/76100a7a259512f600b1b4c34248f3b717dd8b01)　こちらのコミットです

2020-04-15 04:15 UTC, KakoFujimoto commented
#2

[e04d10c](https://github.com/KakoFujimoto/KakoFujimoto/pull/2/commits/e04d10c55ead58641c8406da048a140779144d6f)

2020-04-15 06:24 UTC, piasoratech reviewed
・NEWS部分の文字配置を確認してください。
![image](https://user-images.githubusercontent.com/57445698/79304831-23da8200-7f2d-11ea-9b0f-795281d0c33e.png)

・376px～はPCの画面が見れるようにしておいてください。

2020-04-15 06:32 UTC, KakoFujimoto commented
> ・NEWS部分の文字配置を確認してください。
> ![image](https://user-images.githubusercontent.com/57445698/79304831-23da8200-7f2d-11ea-9b0f-795281d0c33e.png)
> 
> ・376px～はPCの画面が見れるようにしておいてください。

<img width="171" alt="スクリーンショット 2020-04-15 15 28 20" src="https://user-images.githubusercontent.com/60574321/79305364-3d2ffe00-7f2e-11ea-9a89-c01891ed773f.png">
ご指摘の２点を修正致しました。

2020-04-15 07:07 UTC, KakoFujimoto commented
<img width="241" alt="スクリーンショット 2020-04-15 16 06 01" src="https://user-images.githubusercontent.com/60574321/79308200-1e803600-7f33-11ea-95a1-3b15f04ebdfc.png">
画像内の文字配置を修正しました。

2020-04-15 07:12 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-04-16 00:02 UTC, KakoFujimoto commented
TOP以外のレスポンシブデザインを実装しました。

[f2988e7] こちらのコミットです(https://github.com/KakoFujimoto/KakoFujimoto/pull/2/commits/f2988e72b502bb5d65775cf7687f91ca2d09a925)

2020-04-16 02:59 UTC, piasoratech requested changes
・表の右列内の要素の左部分に余白が少ないので調整してください。
![image](https://user-images.githubusercontent.com/57445698/79409732-9c971800-7fd9-11ea-8520-1d9b7cf4b83e.png)
・「お問い合わせ内容」のフォントが違います
![image](https://user-images.githubusercontent.com/57445698/79409771-b2a4d880-7fd9-11ea-88a1-09af3344d1cf.png)

2020-04-16 03:16 UTC, KakoFujimoto commented
<img width="298" alt="スクリーンショット 2020-04-16 12 12 53" src="https://user-images.githubusercontent.com/60574321/79410668-09131680-7fdc-11ea-94b2-94a7e8974878.png">
<img width="275" alt="スクリーンショット 2020-04-16 12 15 15" src="https://user-images.githubusercontent.com/60574321/79410674-0c0e0700-7fdc-11ea-82d9-74a078a413e3.png">
ご指摘点を修正致しました。

2020-04-16 04:40 UTC, piasoratech requested changes
・どのページもヘッダーが追従していないので、確認をお願いします。(指摘漏れです。すいません。)
![image](https://user-images.githubusercontent.com/57445698/79415251-d66f1b00-7fe7-11ea-907c-6471f675702d.png)

・コメントしたので確認をお願いします(こちらの内容も指摘漏れです。すいません。)

2020-04-16 04:40 UTC, piasoratech commented on html-kaguya/contact.html
> +                <textarea name="comment" placeholder="お問い合わせ内容">お問い合わせ内容</textarea><br>
指摘漏れで申し訳ないですが、`value`として「お問い合わせ内容」が入ってしまっているので空にしておきましょう。

2020-04-16 05:00 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +                <textarea name="comment" placeholder="お問い合わせ内容">お問い合わせ内容</textarea><br>
<img width="543" alt="スクリーンショット 2020-04-16 13 59 11" src="https://user-images.githubusercontent.com/60574321/79416412-99f0ee80-7fea-11ea-8b8b-f370c7826462.png">
こちら修正致しました。

2020-04-16 06:45 UTC, KakoFujimoto commented
> ・どのページもヘッダーが追従していないので、確認をお願いします。(指摘漏れです。すいません。)
> ![image](https://user-images.githubusercontent.com/57445698/79415251-d66f1b00-7fe7-11ea-907c-6471f675702d.png)
> 
> ・コメントしたので確認をお願いします(こちらの内容も指摘漏れです。すいません。)

headerの固定、実装致しました。

2020-04-16 07:39 UTC, piasoratech reviewed
・固定したヘッダーは一番上に来るようにしてOKです。(HOMEだけこうなってるみたいです。)
![image](https://user-images.githubusercontent.com/57445698/79428160-b9931180-8000-11ea-9b5e-9e7023e2edef.png)

2020-04-16 07:39 UTC, piasoratech commented on html-kaguya/contact.html
> +                <textarea name="comment" placeholder="">お問い合わせ内容</textarea><br>
`textarea`の場合タグで挟まれている内容が`value`の扱いになるのでタグで挟まれている部分は空っぽ、placeholderに「お問い合わせ内容」と入れる対応があってます。

2020-04-16 08:08 UTC, KakoFujimoto commented on html-kaguya/contact.html
> +                <textarea name="comment" placeholder="">お問い合わせ内容</textarea><br>
<img width="309" alt="スクリーンショット 2020-04-16 16 58 52" src="https://user-images.githubusercontent.com/60574321/79431036-d6c9df00-8004-11ea-96bd-ae1e43b478dc.png">
ご指摘の２点、修正致しました。

2020-04-16 08:47 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
指摘漏れが多くてすいません。

2020-04-16 08:47 UTC, piasoratech commented on html-kaguya/top.html
> +                <textarea name="comment" id="comment">お問い合わせ内容</textarea><br>
すいません。HOME画面もCONTACT画面で指摘した内容で同じように
`placeholder`をすべて設定して、`value`は空に修正しておいてください。

2020-04-16 08:52 UTC, KakoFujimoto commented on html-kaguya/top.html
> +                <textarea name="comment" id="comment">お問い合わせ内容</textarea><br>
いいえ、こちらこそ気づかず申し訳ございません。
修正致しました。

2020-04-16 08:57 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-04-16 08:57 UTC, piasoratech commented on html-kaguya/top.html
>                  <input type="email" name="email" id="email-field" value="メールアドレス"><br>
この２項目もそうですね
`value`ではなく`placeholder`を使用してください。

2020-04-16 09:00 UTC, KakoFujimoto commented on html-kaguya/top.html
>                  <input type="email" name="email" id="email-field" value="メールアドレス"><br>
修正致しました。
何度もすみません…！

2020-04-16 09:01 UTC, piasoratech approved these changes
OKです！
お疲れ様でした！

2020-04-27 09:53 UTC, merged